name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Input image verison'
        required: true
        default: 'latest'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t ${{ github.event.inputs.source_image }} ${{ secrets.PRIVATE_REGISTRY }}/dkhb/meilisearch-mini-dashboard:${{ github.event.inputs.image_version }} .
      
    - name: Log in to private registry
      run: docker login -u "${{ secrets.PRIVATE_REGISTRY_USERNAME }}" -p "${{ secrets.PRIVATE_REGISTRY_PASSWORD }}" ${{ secrets.PRIVATE_REGISTRY }}

    - name: Push Docker image to private registry
      run: docker push ${{ secrets.PRIVATE_REGISTRY }}/dkhb/meilisearch-mini-dashboard:${{ github.event.inputs.image_version }} 

    - name: Log out from private registry
      run: docker logout ${{ secrets.PRIVATE_REGISTRY }}
